### ISSUE TITLE
groups displayed as Undefined

### ISSUE THREAD

**Issue by alka79** [rstrouse/ESPSomfy-RTS#339] opened 2024-04-21 14:22 UTC
### Hardware

ESP32-S2

### Firmware version

v2.4.1

### Application version

v2.4.1

### What happened? What did you expect to happen?

I created 4 groups. The first was created some days ago without any issue, 3 mores today.  
During the process of adding groups today when navigating between tabs, some groups randomly become Undefined. In both the Home tab and in Somfy>Groups.
Refresh the bowser may not hange anything or may display other groups as undefined.
The backup file is correct though. When I reboot the board they are all back to normal... for a while. 
It seems to be a display issue in the app.

Some examples taken in less than 10 minutes time:
![2024-04-21 16 01 35](https://github.com/rstrouse/ESPSomfy-RTS/assets/66568594/ee1ba560-c50c-4ac1-bb25-94ccbc2d96aa)

![2024-04-21 16 04 44](https://github.com/rstrouse/ESPSomfy-RTS/assets/66568594/86b86bb1-2ed2-4a30-bcf6-0bfd09721ebb)

![2024-04-21 16 08 16](https://github.com/rstrouse/ESPSomfy-RTS/assets/66568594/227b13b3-9b87-453e-9749-c1678bd37438)

![2024-04-21 16 07 53](https://github.com/rstrouse/ESPSomfy-RTS/assets/66568594/11666401-9e60-4d98-bc28-898cebaea41c)

### How to reproduce it (step by step)

```bash
randomly appears when navigating between tabs or refreshing the tabs
```

**Comment by rstrouse** [comment] 2024-04-21 19:36
I will have a fix for this soon.  The issue is related to the json serialization libraries.

**Comment by rstrouse** [comment] 2024-04-21 21:20
Update to the v2.4.2 release and you problem should be solved.

**Comment by rstrouse** [comment] 2024-04-22 16:51
I am going to close this for now as I believe we got you sorted.

**Closed by rstrouse** 2024-04-22 16:51 UTC
Labels: bug
