### ISSUE TITLE
Cannot update firmware to version 2.4.5

### ISSUE THREAD

**Issue by hajar97** [rstrouse/ESPSomfy-RTS#406] opened 2024-06-20 19:53 UTC
### Hardware

ESP32

### Firmware version

v2.4.4

### Application version

v2.4.4

### What happened? What did you expect to happen?

HA notified me of new firmware being available. But when I try to install it I get the following error:
Failed to call service update/install. tuple index out of range.
<img width="375" alt="image" src="https://github.com/rstrouse/ESPSomfy-RTS/assets/16057214/aaf28141-6d46-40cb-a81c-5a59b1078c1c">

### How to reproduce it (step by step)

```bash
1. Go to device page
2. Click on firmware update
3. Click on install
```

**Comment by hajar97** [comment] 2024-06-20 20:45
Just noticed that this error only happened when trying to update by connecting to HA via Nabu Casa URL. When using a local IP address, then it has updated without a problem.

**Comment by larserhardsen** [comment] 2024-06-21 07:12
I have the same issue, and I am not using the Nabu Casa URL. The same error is thrown when clicking the backup button on the device's page

**Comment by TranceSetter** [comment] 2024-06-21 08:15
Here the same issue, and as @larserhardsen said it's for both Nabu Case and local URLs.

**Comment by Jezza34000** [comment] 2024-06-21 18:56
This issue is fixed with the last update : https://github.com/rstrouse/ESPSomfy-RTS-HA/releases/tag/v2.4.5

**Comment by hajar97** [comment] 2024-06-21 18:58
Unfortunately I cannot test it as I already updated to the latest version using another approach before. But thanks a lot for looking into it.

**Comment by rstrouse** [comment] 2024-06-30 16:48
I am going to close this.  The cause of this is well understood and addressed in later versions.

**Closed by rstrouse** 2024-06-30 16:48 UTC
Labels: bug
