### ISSUE TITLE
Pinout

### ISSUE THREAD

**Issue by Boosmoo** [rstrouse/ESPSomfy-RTS#353] opened 2024-04-28 11:16 UTC
I have a esp32 c3 super mini and I have a dumb question about the pinout. Should the RX pin on the esp32 be connected to the TX pin of the cc1101 and vise versa? because of tx should be connected to tx because then I cant select the right pins.

**Comment by rstrouse** [comment] 2024-04-28 14:39
The communication between the cc1101 and the ESP32 is not using a serial protocol like rsXXX. The chip communicates over SPI which is the top row of pins in the config pages and the transceiver over gpio.  Simply assign the tx pin to GDO0 on the transceiver and the rx to GDO2.  Ignore the rx and tx assignments those are for another purpose.

**Comment by Boosmoo** [comment] 2024-04-28 14:44
Okay. But its not available in the menu then the tx pin is 21 on my esp but the menu only goes to 20

**Comment by rstrouse** [comment] 2024-04-28 14:59
Use another pin.  The pin marked tx on the c3 is likely a jtag pin.

**Comment by Boosmoo** [comment] 2024-04-28 15:27
Used 9 and 10 but it still doesnt work. It keeps saying radio not initialized.

**Comment by rstrouse** [comment] 2024-04-28 16:02
Then that is not because of the rx and tx pins.  The upper row of pins are the spi chip configuration.  If the pin selection does not match the wiring for sck,mosi,miso,and csn it will not be able to initialize the transceiver.  Just to be sure you did you check the enable radio checkbo?

**Comment by Boosmoo** [comment] 2024-04-28 16:04
Yes I triple checked the connections and the radio is enabled.

**Comment by Boosmoo** [comment] 2024-04-28 16:09
![c286595a99d202f8a3aef6d6caf1f2c90474200d](https://github.com/rstrouse/ESPSomfy-RTS/assets/61115273/5be5dd80-70ff-4d5f-b5ac-4c849036e85e)

I used this pinout.

**Comment by rstrouse** [comment] 2024-04-29 19:57
I would not connect anything to the rx/tx pins on that board.  Most often that is attached to uart0 and is for serial console.

**Comment by Boosmoo** [comment] 2024-04-30 07:45
I connected them to 9 and 10 but it still doesnt work.

**Comment by rstrouse** [comment] 2024-05-01 23:32
According to your pic the wiring is setup like below and does not match the configuration screen.   

| Tr Pin | Color | Func | ESP32 |
| --- | --- | --- | --- |
| 1 | White | GND | GND |
| 2 | Yellow | 3v3 | 3v3 |
| 3 | Purple | GDO0/TX | GPIO7 |
| 4 | Gray | CSN | GPIO9 |
| 5 | Yellow | SCLK | GPIO6 |
| 6 | Orange | MOSI | GPIO4 |
| 7 | Green | MISO | GPIO10 |
| 8 | Brown | GDO2/RX | GPIO5 |

Your configuration looks like it should be like below

![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/47839015/f3602e97-f03e-4f87-9329-026ab7c6b2e3)

**Comment by rstrouse** [comment] 2024-05-11 15:32
@Boosmoo Did you get your issue resolved or is there anything more that I can do to help?

**Comment by Boosmoo** [comment] 2024-05-11 16:29
It still doesnt work

**Comment by rstrouse** [comment] 2024-05-11 17:34
Just in case I missed something, I inventoried your wiring again.  I assume the wire going from pin 3 on the E07-M1101D is gray and terminates at GPIO9.  Please verify that the connections are as I believe they are since I assumed this from your picture.

| Tr Pin | Color | Func | ESP32 |
| --- | --- | --- | --- |
| 1 | White | GND | GND |
| 2 | Yellow | 3v3 | 3v3 |
| 3 | Gray | GDO0/TX | GPIO9 |
| 4 | Purple | CSN | GPIO7 |
| 5 | Orange | SCLK | GPIO4 |
| 6 | Yellow | MOSI | GPIO6 |
| 7 | Brown | MISO | GPIO5 |
| 8 | Green | GDO2/RX | GPIO10 |

If this is how you have it wired and your configuration is as pictured on from your screenshot above we should do some additional troubleshooting.  First update your firmware to v2.4.3 pre.   This uses the Arduino core 2.0.16 which has fixes to the C3 chips.  I did rewire a C3 as above and it worked fine for me on v2.4.2.  However, mine is a Seeed Studio board and not ICBuy board and according to the PRs in the Arduino core there have been fixes for the SPI interface.

Next please look very closely and make sure that no stray strands of wire are connecting especially between GPIO5, GPIO6, or GPIO7.  Look very closely on the transceiver as well.  The Radio not Initialized message happens when the configuration is sent to the E07M1101 over the SPI interface and it cannot be read back.   

If after performing these steps it still does not initialize then you must have either a defective ESP32 or E07M1101D board.  There is no real way to tell which one is goofy.

**Comment by rstrouse** [comment] 2024-05-21 16:56
@Boosmoo have you figured out what the issue is.  I have confirmation that once the wiring was fixed in the issue linked above for the same hardware that it worked fine.

**Comment by Nickduino** [comment] 2024-05-22 11:41
> I would not connect anything to the rx/tx pins on that board. Most often that is attached to uart0 and is for serial console.

I used them myself
![image](https://github.com/rstrouse/ESPSomfy-RTS/assets/9784237/24c822ca-98c7-4257-84ea-118ec11a7bd4)

Are they used only to receive data when the radio is listening?

**Comment by rstrouse** [comment] 2024-05-23 02:41
The rx pin is attached to an interrupt when listening and the tx pin is pulsed to send the frame.   However, the tx pin also receives when listening.  Typically a uart pulls the pins but I think it depends on how it is implemented.

**Comment by Nickduino** [comment] 2024-05-23 10:55
But they're used to listen only, so the fact they're assigned to UART pins should not negatively impact the emitting range of the device, right?

**Comment by Jezza34000** [comment] 2024-05-23 12:52
Hi on my side i just start to build a ESPSomfy RTS with a ESP32-C3 & AS07-M1101S and with this wiring i only receive RF but i can't send command, i've try to switch RX/TX but still same.

| Pin  | RF    | ESP32  |
|--------|---------|--------|
| 1      | GND     | GND    |
| 2      | 3v3     | 3v3    |
| 3      | GDO0/TX | GPIO20 |
| 4      | CSN     | GPIO7  |
| 5      | SCLK    | GPIO4  |
| 6      | MOSI    | GPIO6  |
| 7      | MISO    | GPIO5  |
| 8      | GDO2/RX | GPIO21 |

The AS07-M1101S RF module was working well with a "classic" ESP32

**Comment by rstrouse** [comment] 2024-05-23 19:39
Actually a uart is a transceiver chip where TX pin is pulled low.   I don't know if this is done even if the UART is not enabled or if this is simply the wiring.  I guess it depends on its implementation on the board.

**Comment by Nickduino** [comment] 2024-05-24 11:29
I mean by ESPSomfy. The use of the TX/RX pins is for **receiving** frames from other remotes, right? When the CC1101 is receiving.

Said differently, can you omit the TX/RX connection and still control the blinds?

**Comment by Nickduino** [comment] 2024-05-25 14:50
Alright, thank you!

I had made this assumption because at some point I made a mistake and inverted the Tx and Rx pins but the frames were still sent. Not received, though.

**Comment by rstrouse** [comment] 2024-05-25 15:51
Yeah most of us have been through through some level of full duplex serial communication and its hard to get the twisted pair out of our heads.

Unfortunately, with some of the board manufacturers they leave out important details regarding their implementation.  A simple footnote on the pinout diagram would suffice.  Especially, when they solder their own peripherals onto the board.

**Comment by rstrouse** [comment] 2024-06-15 16:43
@Boosmoo I am going to close this as I assume you have gotten the issue resolved by now.

**Closed by rstrouse** 2024-06-15 16:43 UTC
